export const paths = {
  auth: {
    root: "/auth",
    login: "/auth/login",
    register: "/auth/register",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    config: "/admin/config",
    support: "/admin/support",
  },
  user: {
    root: "/user",
    landingPage: "/user",
    inicio: "/user/inicio",
    servidores: "/user/servidores",
    servidoresProcesando: "/user/servidores/procesando",
    servidoresRecomendaciones: "/user/servidores/recomendaciones",
    perfil: "/user/perfil",
    panelDeAlertas: "/user/panel-de-alertas",
    dashboard: "/user/dashboard",
    rendimiento: "/user/rendimiento",
    configuracion: "/user/configuracion",
    alertas: "/user/alertas",
    support: "/user/support",
  },
  root: "/",
} as const;
